import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/moving-border";
import Image from "next/image";
import Footer from "@/components/Footer";
import ShimmerButton from "@/components/magicui/ShimmerButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`bg-black ${inter.className}`}>
        <nav className="flex justify-between items-center text-[0.7rem]  md:-mt-3 pl-2 md:pl-5 md:text-xl">
        <Link href="/">
              <Image 
                src="https://res.cloudinary.com/dfhj4i9hd/image/upload/v1721929345/CSI%20Website/logo_f1pruv.jpg" 
                alt="Logo" width={130} height={130} 
                />
            </Link>
          <div className="flex items-center space-x-4">
            
            <div className="flex justify-center text-white space-x-4 md:space-x-10">
              <Link href="/team"><div>TEAM</div></Link>
              <Link href="/events"><div>EVENTS</div></Link>
              <Link href="/gallery"><div>GALLERY</div></Link>
              <Link href="/about"><div>ABOUT</div></Link>
            </div>
          </div>
          <div className="">
            <div className=" pl-2 z-10 w-8/12  items-center justify-center">
              <ShimmerButton borderRadius="15px" className="shadow-2xl">
                <span className="whitespace-pre-wrap text-center  font-medium leading-none tracking-tight text-white dark:from-white dark:to-slate-900/10 lg:text-lg">
                  BROCHURE
                </span>
              </ShimmerButton>
            </div>
          </div>
        </nav>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
